spring.application.name=ProfileMS

server.port=9100
spring.datasource.url=jdbc:mysql://localhost:3306/profiledb
spring.datasource.username=root
spring.datasource.password=Harsh@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

DOCTOR_ALREADY_EXISTS=Doctor with the same name already exists.
DOCTOR_NOT_FOUND=Doctor not found with the given id.


PATIENT_ALREADY_EXISTS=Patient with the same name already exists.
PATIENT_NOT_FOUND=Patient not found with the given id.