spring.application.name=PharmacyMS
server.port=9300
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacydb
spring.datasource.username=root
spring.datasource.password=Harsh@123



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

MEDICINE_ALREADY_EXIST=Medicine with same name and dosage already exist
MEDICINE_NOT_FOUND=Medicine not found