spring.application.name=GatewayMS
server.port=9000


spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin RETAIN_UNIQUE

spring.cloud.gateway.globalcors.cors-configurations[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations[/**].allowCredentials=true

#UserMS

spring.cloud.gateway.routes[0].id=UserMS
spring.cloud.gateway.routes[0].uri=lb://UserMS
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[0].filters[0]=TokenFilter

#ProfileMS

spring.cloud.gateway.routes[1].id=ProfileMS
spring.cloud.gateway.routes[1].uri=lb://ProfileMS
spring.cloud.gateway.routes[1].predicates[0]=Path=/profile/**
spring.cloud.gateway.routes[1].filters[0]=TokenFilter



#AppointmentMS

spring.cloud.gateway.routes[2].id=AppointmentMS
spring.cloud.gateway.routes[2].uri=lb://Appointment
spring.cloud.gateway.routes[2].predicates[0]=Path=/appointment/**
spring.cloud.gateway.routes[2].filters[0]=TokenFilter


#PharmacyMS

spring.cloud.gateway.routes[3].id=PharmacyMS
spring.cloud.gateway.routes[3].uri=lb://PharmacyMS
spring.cloud.gateway.routes[3].predicates[0]=Path=/pharmacy/**
spring.cloud.gateway.routes[3].filters[0]=TokenFilter

#MediaMS

spring.cloud.gateway.routes[4].id=media
spring.cloud.gateway.routes[4].uri=lb://media
spring.cloud.gateway.routes[4].predicates[0]=Path=/media/**
spring.cloud.gateway.routes[4].filters[0]=TokenFilter