spring.application.name=Appointment

server.port=9200
spring.datasource.url=jdbc:mysql://localhost:3306/appointmentdb
spring.datasource.username=root
spring.datasource.password=Harsh@123



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



APPOINTMENT_NOT_FOUND=Appointment not found with the given id.
APPOINTMENT_ALREADY_CANCELLED=Appointment is already cancelled.

APPOINTMENT_RECORD_NOT_FOUND=Appointment record not found with the given id.
APPOINTMENT_RECORD_ALREADY_EXISTS=Appointment record already exists for the given appointment id.

DOCTOR_NOT_FOUND=Doctor not found with the given id.
PATIENT_NOT_FOUND=Patient not found with the given id.